---
title: "The Cambridge R-User Group Returns!"
output: html_document
date: "The Emperor Pub, Monday 27th October 2014 - 6pm - 8:30 (ish)"
---
```{r echo=FALSE,warning=FALSE,fig.width=7,fig.height=7}

suppressPackageStartupMessages(library(wordcloud))
library(RColorBrewer)

t <- read.delim("functionCloud-sqrt.txt", as.is = TRUE)
t$freq = round(t$freq)
## add CambR
t <- rbind(list("CambR.org.uk", 300), t)
## decrease stop
t[t$fun == "stop", "freq"] <- 60 ## was 123

## color scheme
pal <- brewer.pal(9,"Blues")[5:9]
wordcloud(t$fun, t$freq, c(6,.1), max.words = 200, random.order = FALSE, colors = pal)
```

# Featuring talks on:

## Preparing slides using Slidify / markdown - Andrew Caines

## The [dplyr](http://cran.rstudio.com/web/packages/dplyr/vignettes/introduction.html) package for efficient manipulation of data frames - TBC

#Note new venue - The Emperor pub, Hills Road, Cambridge

```{r echo=FALSE,results='asis'}
suppressPackageStartupMessages(library(googleVis))
df <- data.frame(Postcode = "CB2 1NW", Tip = "The Emperor Pub")
M <- gvisMap(df, "Postcode", "Tip", options=list(showTip=TRUE, mapType='normal',enableScrollWheel=TRUE,zoomLevel=16))
print(M,"chart")
```

For more info:

`mark.dunning@cruk.ac.uk`